//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListComparer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ListComparer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} columns expected, but {2} found.
        /// </summary>
        internal static string ColumnMismatch {
            get {
                return ResourceManager.GetString("ColumnMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column{0}.
        /// </summary>
        internal static string ColumnNo {
            get {
                return ResourceManager.GetString("ColumnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in {0} at line {1}: .
        /// </summary>
        internal static string ErrorAt {
            get {
                return ResourceManager.GetString("ErrorAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid number of columns is established.
        /// </summary>
        internal static string InvalidNumColumns {
            get {
                return ResourceManager.GetString("InvalidNumColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List{0}.
        /// </summary>
        internal static string ListNumber {
            get {
                return ResourceManager.GetString("ListNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greather than zero.
        /// </summary>
        internal static string MustBeGreatherThanZero {
            get {
                return ResourceManager.GetString("MustBeGreatherThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No separator chars are established.
        /// </summary>
        internal static string NoSeparatorChars {
            get {
                return ResourceManager.GetString("NoSeparatorChars", resourceCulture);
            }
        }
    }
}
